replace ipl image with cv Mat
ntnu-arl/darknet pull request #1
Opened 2021-01-18 16:32 UTC by Samu24

PR removes deprecated `IplImage` and use `cv::Mat` instead. C Macros have been updated as well

2021-01-18 16:47 UTC, marco-tranzatto requested changes

2021-01-18 16:47 UTC, marco-tranzatto commented on src/image_opencv.cpp
> +                float val = copy.data[c*im.h*im.w + y*im.w + x];
can we compute `im.h*im.w` outside the 3 for loops, as this is constant for the same matrix?

2021-01-18 16:47 UTC, marco-tranzatto commented on src/image_opencv.cpp
> +                m.data[y*im.w*im.c + x*im.c + c] = (unsigned char)(val*255);
same here, can we compute `im.w*im.c` outside the for loops?

2021-01-19 07:46 UTC, marco-tranzatto approved these changes

2021-01-19 19:58 UTC, HuanNguyenARL approved these changes
looks good to me

2021-02-05 14:05 UTC, merged